# Generated by Django 5.1 on 2024-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlight_price',
            field=models.PositiveIntegerField(default=0, blank=True, null=True),
        ),
    ]
