# Generated by Django 5.1 on 2024-09-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_highlight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highlight_price',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
    ]
