from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('change-password/',views.change_password,name='change-password'),
    path('forgot-password/',views.forgot_password,name='forgot-password'),
    path('verify-otp/',views.verify_otp,name='verify-otp'),
    path('new-password/',views.new_password,name='new-password'),    
    path('profile/',views.profile,name='profile'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('seller-product/',views.seller_product,name='seller-product'),
    path('seller-add-category/',views.seller_add_category,name='seller-add-category'),
    path('delete-category/<int:id>/',views.delete_category,name='delete-category'),
    path('seller-product-category/',views.seller_product_category,name='seller-product-category'),
    path('seller-add-product/',views.seller_add_product,name='seller-add-product'),
    path('seller-view-product/<int:id>/',views.seller_view_product,name='seller-view-product'),
    path('seller-edit-product/<int:id>/',views.seller_edit_product,name='seller-edit-product'),
    path('seller-delete-product/<int:id>/',views.seller_delete_product,name='seller-delete-product'),
    path('product-detail/<int:id>/',views.product_detail,name='product-detail'),
    path('category/<str:cate>/',views.category_products,name='category-products'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('user-wishlist/<int:id>/',views.user_wishlist,name='user-wishlist'),
    path('remove-wishlist/<int:id>/',views.remove_wishlist,name='remove-wishlist'),    
    path('cart/',views.cart,name='cart'),
    path('user-cart/<int:id>/',views.user_cart,name='user-cart'),
    path('remove-cart/<int:id>/',views.remove_cart,name='remove-cart'),
    path('change-qty/',views.change_qty,name='change-qty'),
    path('create-checkout-session/', views.create_checkout_session, name='payment'),
    path('payment-success/<str:session_id>/', views.payment_success, name='payment-success'),
    path('success.html/', views.success,name='success'),
    path('cancel.html/', views.cancel,name='cancel'),
    path('order-list/', views.order_list,name='order-list'),
    path('ajax/validate_email/', views.validate_email, name='validate_email'),
    path('ajax/validate_passwords/', views.validate_passwords, name='validate_passwords'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('seller-orders/', views.seller_orders, name='seller-orders'),
    path('orders/<int:order_id>/', views.seller_order_detail, name='seller_order_detail'),
    path('seller-inventory/', views.seller_inventory, name='seller-inventory'),
    path('update-inventory/<int:id>', views.update_inventory, name='update-inventory'),
]
